set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

iab errcheck if err != nil {<cr>return err<cr>}<cr>
iab errlog if err != nil {<cr>log.Errorf("do what err:%s", err)<cr>return err<cr>}<cr>
iab todo ::paas_army todo:

colo ron
